### ISSUE TITLE
raise NotADirectoryError('Specified path must be a directory')

### ISSUE THREAD

**Issue by ggdayup** [lunixoid/dbibackend#5]
Environment:
macOS Big Sur Version 11.4
MacBook Pro (13-inch, M1, 2020)

python --version
Python 2.7.16

MTP Mode is successful, I can transfer files to the switch.

But can't start DBI BACKEND on Macbook.

Here's the error message:

**$ python3 dbibackend.py tites_dir_path**
_Traceback (most recent call last):
  File "/Users/ggdayup/Downloads/dbibackend-master/dbibackend/dbibackend.py", line 210, in <module>
    main()
  File "/Users/ggdayup/Downloads/dbibackend-master/dbibackend/dbibackend.py", line 201, in main
    raise NotADirectoryError('Specified path must be a directory')
NotADirectoryError: Specified path must be a directory_

Would you please help to check?

**Comment by lunixoid** [comment]
> Environment:
> macOS Big Sur Version 11.4
> MacBook Pro (13-inch, M1, 2020)
> 
> python --version
> Python 2.7.16
> 
> MTP Mode is successful, I can transfer files to the switch.
> 
> But can't start DBI BACKEND on Macbook.
> 
> Here's the error message:
> 
> **$ python3 dbibackend.py tites_dir_path**
> _Traceback (most recent call last): File "/Users/ggdayup/Downloads/dbibackend-master/dbibackend/dbibackend.py", line 210, in main() File "/Users/ggdayup/Downloads/dbibackend-master/dbibackend/dbibackend.py", line 201, in main raise NotADirectoryError('Specified path must be a directory') NotADirectoryError: Specified path must be a directory_
> 
> Would you please help to check?

Hi, thanks for your replying.
Could you please send me an output of
stat tites_dir_path?

**Comment by ggdayup** [comment]
$ stat tites_dir_path
stat: tites_dir_path: stat: No such file or directory

$ python3 --version
Python 3.9.5

**Comment by lunixoid** [comment]
Please, create directory tites_dir_path and put titles inside.

**Comment by lunixoid** [comment]
titles_dir_path is just an example, you have to change it to your directory
