### ISSUE TITLE
Empty list

### ISSUE THREAD

**Issue by erralb** [lunixoid/dbibackend#6]
Hi, I am trying to install xci files from usb on Mac OS 11.5.2.
I installed libusb with Homebrew and pyusb with pip3.

The backend is starting and connecting to the switch but the game list is empty.
I tried absolute and relative paths to the games folder but on the Switch nothing shows, any idea ? Cheers

**Comment by lunixoid** [comment]
DBI does not work with xci files, only nsp/nsz.

**Comment by erralb** [comment]
Ok sorry, I had read on a forum that DBI added support for xci files, people spreading a wrong info !

**Comment by lunixoid** [comment]
> Ok sorry, I had read on a forum that DBI added support for xci files, people spreading a wrong info !

I've found that DBI got support for xci and xcz files, so i've to update dbibackend.
Please, check next version.

**Comment by bhagatparwinder** [comment]
So I tried the latest from master. I'm using it on Mac with Ventura. I don't get any list items on the switch. The terminal on mac says:

> Entering command loop
> Get list

That is it.

**Comment by lunixoid** [comment]
> So I tried the latest from master. I'm using it on Mac with Ventura. I don't get any list items on the switch. The terminal on mac says:
> 
> > Entering command loop
> > Get list
> 
> That is it.

What's your setup?
Do you have libusb installed?
What's insied of your directory?

**Comment by bhagatparwinder** [comment]
What's your setup?
macOS Venture 13.3. Using the latest from `master`

Do you have libusb installed?
Yes, `libusb 1.0.26`

What's insied of your directory?
I have tried it with XCI files and NSP files.

**Comment by lunixoid** [comment]
> I have tried it with XCI files and NSP files.

Could you try with folder NSP files only inside?
I'm not sure about mixed folder list output.
