### ISSUE TITLE
Remove breaking code 

### ISSUE THREAD

**Issue by kerambit** [lunixoid/dbibackend#8]
I have macOS  ventura 13.5.2 (22G91) and using M2 chip and the program won't work with your code. After connection and starting it's reject connection and broke script && dbi pool
Looks like this line https://github.com/lunixoid/dbibackend/blob/master/dbibackend/dbibackend.py#L41 breaks execution of the  whole application.
I removed it from the code and it works fine.
It's really needed?

**Comment by lunixoid** [comment]
No, it just for sure if usb device in undefined state.

**Comment by kerambit** [comment]
I can make pr to fix this bug and close the issue

**Comment by lunixoid** [comment]
It would be great.

**Comment by kerambit** [comment]
Push failed 
remote: Permission to lunixoid/dbibackend.git denied to kerambit. unable to access 'https://github.com/lunixoid/dbibackend/': The requested URL returned error: 403

**Comment by lunixoid** [comment]
> Push failed
> remote: Permission to lunixoid/dbibackend.git denied to kerambit. unable to access 'https://github.com/lunixoid/dbibackend/': The requested URL returned error: 403

Please, make a fork of this project and send pr to develop branch. I’ll make the next patch release and add you to contributors.

**Comment by kerambit** [comment]
Sure, check it up https://github.com/lunixoid/dbibackend/pull/9

**Comment by kerambit** [comment]
Looks great. I suppose you can merge develop into master 
Closing this issue
